### ISSUE TITLE
504 Gateway Timeout by Cert Manager when using zero SSL

### ISSUE THREAD

**Issue by nswarnkar** [zerossl/zerossl#9]
Hello,

We are using paid Zero SSL account. and some certificate taking long time. Recently we observed that certificate was not issued even after 72minutes. Domain name against which we are generating certificate is valid, and pingable. 
We observed cert manager saying gateway timeout.

I0603 05:00:47.436361 1 sync.go:143] cert-manager/controller/orders "msg"="Finalizing Order as order state is 'Ready'" "resource_kind"="Order" "resource_name"="cert-6313b09c122fe476-8r9q7-2487832066" "resource_namespace"="wg-connections" I0603 05:00:48.309471 1 sync.go:224] cert-manager/controller/orders "msg"="Fetching Order metadata from ACME server" "resource_kind"="Order" "resource_name"="cert-6313b09c122fe476-8r9q7-2487832066" "resource_namespace"="wg-connections" E0603 05:00:48.480760 1 controller.go:158] cert-manager/controller/orders "msg"="re-queuing item due to error processing" "error"="error syncing order status: 504 : 504 Gateway Time-out" "key"="wg-connections/cert-6313b09c122fe476-8r9q7-2487832066"

Please suggest.

**Comment by nswarnkar** [comment]
Zero SSL mentioned : "We were experiencing delays in issuing 90-day and 1-year certificates. Certificate issuance backlog has cleared and is functioning as expected.". So this is support issue, not related to code.

**Comment by fu-sen** [comment]
You seem to be confused for a while. I also check this comment.
https://github.com/zerossl/zerossl/issues/8#issuecomment-853570457

The ZeroSSL ACME API is currently complaining. There is no doubt that this has caused your problem.
https://status.zerossl.com/

In case of such a situation, ACME clients will usually try to update from a deadline stage.
Please wait for the API to recover.

**Comment by fu-sen** [comment]
t seems that the ZeroSSL ACME API server issue has been addressed.
https://status.zerossl.com/8200003/2021/06

After checking the current status, you will be able to try the script again.

**Comment by nswarnkar** [comment]
> You seem to be confused for a while. I also check this comment.
> [#8 (comment)](https://github.com/zerossl/zerossl/issues/8#issuecomment-853570457)
> 
> The ZeroSSL ACME API is currently complaining. This is causing your problem.
> https://status.zerossl.com/8200003/2021/06
> 
> n case of such a situation, ACME clients will usually try to renew for a few days earlier than the expiration date.
> Please wait for the API to recover.
I was not confused about two issues, earlier one was delay in certificates issuance, which boiled down DNS problem. While later was indicating the sure shot problem at zerossl service, that why created separate issue. 

By the way site says it was down for approx 2 hours, but  we were not able to generate certificates atleast for 4 hours. 
Now it look fine. Thanks for your response.

**Comment by fu-sen** [comment]
I received an announcement from ZeroSSL. If you issue ZeroSSL in the next few days, there are times when it cannot be issued due to maintenance.
https://help.zerossl.com/hc/en-us/articles/900006733066
